### ISSUE TITLE
Autonomous Navigation - Map alignment issue

### ISSUE THREAD

**Issue by dhruvtya** [centauri-robotics/ck9#1]
So after following instructions of connecting remotely to the robot, testing functioning of hardware and mapping with teleop, we created a map file.

But when we try to use that map file for autonomous navigation (using roslaunch ck9_navigation navigate.launch map_file:=*path_to_map*), and then run rviz on the remote pc, the map is not aligned to the lidar boundaries or the localization.

![1](https://user-images.githubusercontent.com/72576161/109924764-cd159c80-7ce6-11eb-8292-fc2d5e4cd79d.JPG)
 

To be clear, if the robot position is seen with respect to the lidar values, the localization is correct. It's just that the lidar values should be aligned with the map boundaries, which is not happening. Due to this giving navigation goals is also difficult.

Also tried moving around with teleop, but the angle offset between lidar and map boundaries persists. And this angle offset is not constant. If i close this operation, move the robot a bit, then start navigation again, the map will be oriented in a different way with a different offset.

One other thing we tried, mapped the room from a single standstill position, then from that same position ran the navigation launch. In this, the map was aligned with the lidar values, as seen below

![3](https://user-images.githubusercontent.com/72576161/109925120-575e0080-7ce7-11eb-83c0-14f6128e11fe.JPG)

No changes/customizations have been made to the code from the repo.

**Comment by jash101** [comment]
@dhruvtya this is the expected behaviour in ROS.
When you start navigation, the initial pose estimate is considered 0,0. This means it will consider itself to be at the origin of the map frame. 

When you map from a standstill and navigate from the same position, your origin matches in both cases, hence the alignment. 

In other cases, you'd have to give an initial pose estimate, which can be easily done in rViz.
For more details refer: https://en.wikipedia.org/wiki/Wake-up_robot_problem?wprov=sfla1
